# Generated by Django 4.2.10 on 2024-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_user_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Загрузите фото'),
        ),
    ]
