# Generated by Django 4.2.10 on 2024-02-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Напишите коментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_hotels', to='Hotel.hotel')),
            ],
        ),
    ]
